document.getElementById('generate-btn').addEventListener('click', generateLoremIpsum);
document.getElementById('copy-btn').addEventListener('click', copyToClipboard);

function generateLoremIpsum() {
    const paragraphs = document.getElementById('paragraphs').value;
    const output = document.getElementById('output');
    const copyBtn = document.getElementById('copy-btn');
    const scrollableCard = document.querySelector('.scrollable-card');
    const loremTexts = [
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus mollis orci, sed rhoncus sapien nunc eget odio. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus. Praesent pharetra massa at tellus sodales, ut porttitor turpis gravida. In ac justo nulla. Morbi ut tortor in orci laoreet convallis. Quisque euismod justo in erat interdum, ac scelerisque eros malesuada. Sed vestibulum, lectus non ullamcorper imperdiet, erat eros congue sapien, nec aliquet elit mi ac neque.",
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Nullam ac magna at odio fringilla consectetur id in justo. Suspendisse non orci ac metus congue fringilla. Morbi suscipit nisl sed orci ornare, id gravida eros tincidunt. Sed cursus, lacus ac condimentum feugiat, neque risus placerat odio, a efficitur magna lectus ac ligula.",
        "Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In dui magna, posuere eget, vestibulum et, tempor auctor, justo. In ac felis quis tortor malesuada pretium. Donec euismod quam id libero dapibus, nec placerat erat venenatis. Integer venenatis, urna id fermentum fermentum, arcu libero dictum eros, a eleifend nunc mauris non leo. Nullam a lacus et dui scelerisque feugiat. Vestibulum et fringilla lorem.",
        "Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus. Morbi non sapien at odio vehicula sollicitudin. Etiam vel erat venenatis, laoreet purus vel, tincidunt mi. Ut scelerisque, elit vel condimentum gravida, tortor felis vehicula ante, non hendrerit sem felis sit amet ligula.",
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis dui at dolor tempor interdum. Sed vehicula, nunc non tincidunt sodales, urna lectus fringilla risus, et ultrices lectus felis vitae enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam in magna a odio sollicitudin ornare. Integer et ornare orci. Ut volutpat lectus magna, eu volutpat urna volutpat et. Proin tincidunt cursus ligula, in pellentesque nulla bibendum sit amet. Duis efficitur magna at lacus hendrerit, non scelerisque magna dictum. Aenean aliquet nisl nec neque consectetur, in interdum orci cursus. Curabitur maximus venenatis nisl in vestibulum. Suspendisse in libero nulla. Integer ac felis eget lectus posuere lacinia. Duis ultrices turpis sed ante aliquam tincidunt.",
        "Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur at velit nec neque lacinia dictum. Aliquam dignissim odio eu nulla feugiat maximus. Integer facilisis, arcu a consectetur tincidunt, velit urna aliquet nulla, vel fermentum orci sapien vel turpis. Suspendisse vel dictum eros, nec efficitur sapien.",
        "Curabitur sodales ligula in libero. Sed dignissim lacinia nunc. Curabitur tortor. Pellentesque nibh. Aenean quam. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. Vivamus sed arcu dui. Vestibulum elementum orci sit amet odio faucibus rhoncus. Ut nec ligula nec lorem ultricies aliquam. Etiam venenatis felis non nisi malesuada, a cursus ex dignissim.",
        "Vestibulum suscipit nulla quis orci. Nam ipsum risus, rutrum vitae, vestibulum eu, molestie vel, lacus. Sed diam eget risus varius blandit sit amet non magna. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Praesent tincidunt lacus vel enim faucibus, non ultrices augue viverra. Cras sodales lorem sit amet odio vehicula, et faucibus justo facilisis. Etiam accumsan metus nec massa tempus, eget laoreet ex rhoncus.",
        "Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam nec ante. Sed lacinia, urna non tincidunt mattis, tortor neque adipiscing diam, a cursus ipsum ante quis turpis. Nulla facilisi. Ut fringilla. Suspendisse potenti. Nunc feugiat mi a tellus consequat imperdiet. Vestibulum sapien. Proin quam. Etiam ultrices. Nulla facilisi. Phasellus non dui at purus cursus convallis. Maecenas suscipit mauris nec sem blandit, sed suscipit velit egestas.",
        "Morbi ut blandit risus. Donec mollis, arcu ut molestie tristique, tortor erat condimentum mi, non elementum nunc metus at metus. Nullam auctor, justo sit amet varius mollis, metus quam blandit nunc, ac cursus libero turpis vel lorem. Curabitur non semper velit. Proin bibendum, urna vel dictum varius, lorem velit feugiat purus, a congue ex quam a turpis. Nunc viverra nisi non urna sodales, vel volutpat lacus auctor. In sed nisi at libero posuere scelerisque. Aliquam erat volutpat. Vivamus ac orci vel ipsum sodales cursus.",
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, justo ut ultrices pulvinar, orci turpis laoreet nunc, sed dictum eros risus non libero. In dapibus, lacus vel ultricies consectetur, magna libero pellentesque sem, et interdum mauris nisl ut nisi. Nam vitae arcu a ligula dictum pharetra. Fusce vel vehicula nunc. Curabitur vestibulum dolor ut elit viverra, a pharetra lacus facilisis. Phasellus tempor nisi ac turpis tempor, in sollicitudin libero congue. Ut vehicula, erat nec condimentum dictum, dui metus lacinia mi, id porttitor risus urna eget justo. Aenean ac lectus at nulla varius dignissim. Sed lobortis augue id vehicula ornare. Sed tempus scelerisque est, sit amet malesuada eros pulvinar id.",
        "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aenean consequat efficitur diam, at scelerisque libero ullamcorper id. Proin dictum metus vitae orci gravida, non sodales magna cursus. Nam a felis id leo vulputate auctor. Integer euismod dapibus lacus, sed lacinia enim mollis a. Phasellus dictum magna sed nibh elementum, et varius lectus consequat. Ut consectetur purus a mi cursus, ac pulvinar lectus scelerisque. Sed ac justo non sapien vehicula convallis. Maecenas eget orci a sapien lobortis varius. Sed vitae magna ut purus viverra tincidunt sed non lectus.",
        "Curabitur id fermentum metus. Integer ut odio et erat vestibulum porttitor. Nullam bibendum massa eget lacus auctor, a tincidunt sapien efficitur. Sed eget sapien in justo aliquet gravida at id odio. In id erat neque. Praesent scelerisque est sed elit laoreet, a elementum purus malesuada. Fusce tincidunt, nulla vel efficitur convallis, turpis magna luctus ligula, vel volutpat elit turpis ut dolor. Quisque aliquet, ligula sed tempus iaculis, lorem magna cursus augue, at bibendum sapien magna sit amet magna. Nunc ornare lorem vitae sapien condimentum, eget tempor sapien sagittis. Sed efficitur metus et lacus fermentum laoreet. Cras id est ut ligula fringilla fermentum in non velit.",
        "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?",
        "Phasellus faucibus enim vel ultricies laoreet. Vivamus vitae tortor vel risus sodales lobortis. Aliquam erat volutpat. Vivamus euismod auctor massa ac tempor. Nam dictum justo eget mauris aliquet cursus. Quisque a felis vel lorem fermentum ullamcorper. Integer cursus, orci non convallis scelerisque, leo lectus tincidunt arcu, ut fermentum dui felis et odio. Nam dapibus nisi in augue lacinia, nec ultrices arcu commodo. Donec lacinia, elit eu pharetra bibendum, est ligula varius enim, nec tempor orci risus sit amet magna. Suspendisse potenti. Cras eget nibh ac lectus dictum dictum ut vitae felis. Integer eget ligula eu est bibendum venenatis ac eget felis.",
        "Etiam non purus dignissim, pulvinar libero nec, venenatis orci. Morbi et risus et erat interdum varius. Integer sit amet interdum libero. Cras eget efficitur lorem. Curabitur sit amet fermentum mauris. Praesent a magna non ipsum egestas ultrices. Quisque scelerisque, arcu ac viverra lobortis, ipsum arcu venenatis magna, in scelerisque turpis purus non magna. Vivamus blandit quam nec tellus ultricies, sit amet cursus nulla viverra. Sed varius leo nec urna pulvinar, sit amet vehicula dolor sollicitudin. Nam et eros ligula. Vivamus auctor, lectus et ultricies elementum, leo lectus vestibulum nulla, vitae ultrices turpis felis eget eros.",
        "Proin vehicula nunc sit amet libero auctor, vitae fermentum tortor bibendum. Vivamus ac tortor et urna varius sollicitudin. Donec efficitur justo id ipsum vulputate, a consequat eros interdum. Fusce tincidunt vehicula diam, id posuere ipsum finibus sed. Phasellus molestie lacus sed suscipit hendrerit. Aenean malesuada magna sit amet ultricies venenatis. Fusce quis metus eget libero vehicula consequat. Integer id felis quis metus dapibus lacinia. Nulla facilisi. Phasellus ac erat sapien. Curabitur vitae arcu massa. In hac habitasse platea dictumst. Duis tempor lacus sed sapien eleifend, in accumsan ligula facilisis. Donec ullamcorper ex sit amet diam dignissim, et feugiat enim convallis.",
        "Fusce ut mi at tortor posuere sodales. Integer vehicula, justo a feugiat facilisis, risus lectus aliquam felis, a luctus tortor mi sit amet sapien. Donec a auctor tortor. Nunc pharetra felis nec lacinia aliquam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent id magna nec ligula aliquet luctus. Aenean vehicula, erat a tincidunt elementum, elit mi viverra elit, non cursus dolor neque ut lacus. In et massa sed lacus dignissim aliquet id ac elit. Vivamus ac consequat metus, nec gravida ex. Curabitur fringilla justo vel turpis egestas, vitae gravida nisi vulputate. Etiam in interdum ligula. Nulla facilisi. Sed id dui a nisi suscipit eleifend.",
        "Nullam at dui volutpat, vehicula nulla a, aliquet ligula. Phasellus sollicitudin mollis turpis, et dignissim dolor ultricies eget. Pellentesque euismod nibh quis vehicula scelerisque. Fusce et arcu et eros ultrices convallis. Nullam nec elit bibendum, vehicula libero id, aliquam leo. Quisque at purus at erat aliquam scelerisque non a leo. Nam vel nisi ut ante vehicula hendrerit. Sed consequat nisl ut lacus bibendum dignissim. Etiam sit amet tincidunt odio, nec interdum risus. Phasellus vel varius lorem, sit amet sollicitudin metus. Cras efficitur bibendum libero, et maximus elit ullamcorper sed. Pellentesque sagittis sollicitudin velit, ut tempor libero congue at.",
    ];


    output.innerHTML = ''; 

    for (let i = 0; i < paragraphs; i++) {
        const randomIndex = Math.floor(Math.random() * loremTexts.length);
        const paragraph = document.createElement('p');
        paragraph.textContent = loremTexts[randomIndex];
        output.appendChild(paragraph);
    }

    copyBtn.style.display = 'inline-block';

    scrollableCard.style.display = 'block';
}

function copyToClipboard() {
    const output = document.getElementById('output');
    const range = document.createRange();
    range.selectNode(output);
    window.getSelection().removeAllRanges(); 
    window.getSelection().addRange(range);
    

    try {
        document.execCommand('copy');
        showNotification('Texte copié dans le presse-papiers', 'success');
    } catch (err) {
        showNotification('Impossible de copier le texte', 'error');
    }

    window.getSelection().removeAllRanges(); 
}

function showNotification(message, type) {
    const notification = document.getElementById('notification');
    notification.textContent = message;
    notification.className = `notification ${type} show`;

    setTimeout(() => {
        notification.className = 'notification';
    }, 3000); 
}
